language: python
python:
  - "nightly"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy3"
  - "pypy"
install:
  - "pip install -r requirements.txt -r requirements-tests.txt"
  - "python setup.py install"
script: "python setup.py nosetests  && flake8 arbiter tests"
after_success:
  - coveralls
