language: python
sudo: false
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=flake8
matrix:
  allow_failures:
    # Currently, allowing pypy3 and py35 to fail
    # cause travis doesn't seem to support them properly by default.
    - env: TOXENV=pypy3
    - env: TOXENV=py35
  fast_finish: true
install:
  - travis_retry pip install tox==1.6.1
script:
  - travis_retry tox
after_success:
  - coveralls
